name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Build
        run: ./gradlew jsBrowserProductionWebpack
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build/distributions
